project: 
  type: website
  
website: 
  page-navigation: true
  title: "Making sharable documents with Quarto" 
  site-url: "https://openscapes.github.io/quarto-website-tutorial" 
  repo-url: https://github.com/openscapes/quarto-website-tutorial 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2022"
    
  sidebar:
    logo: "images/ds-community-logo.jpg"
    pinned: true
    align: center
    tools: 
      - icon: slack
        href: https://join.slack.com/t/ds-communitybuilders/shared_invite/zt-1igdvgnhi-B_U1ra3HIy7axIJyv5wS1A
        text: "Data Science Community Builder Slack"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Website GitHub"
      - icon: link
        href: https://evt.to/aihmgeaow
        text: "Community Builder Coffee Hour"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - explore.qmd
      - building-engagement.qmd
      - href: common-challenges.qmd
        text: Common challenges to explore together
      - href: learning-more.qmd
        text: Community resources & examples


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
