---
title: Getting started
---

The book [Checklist Manifesto](http://atulgawande.com/book/the-checklist-manifesto/), shares that experts (whether doctors, pilots, or whoever) need checklists-literally- written guides that walk them through the steps of any complex procedure. Here is a starting point for building a community from the ground up.

::: {.callout-note collapse="false"}
## Checklist for starting a community
1.  Decide that you want to start an internal data science community

2.  Identify people that you would invite to this community

3.  Find someone that would be interested in leading it with you

4.  Create a format that you will use to keep everyone connected (Slack, Teams, Yammer, Discord, etc.)

5.  Identify an event that you'd like to hold consistently (maybe once a month to start)

6.  Create an invitation for the event (could use a simple Email Invite, or use a tool like [AddEvent](https://addevent.com), [Meetup](https://meetup.com), etc.)

7.  Create a logo for the event or recurring series using a tool like [Canva](https://canva.com)

8.  Personally invite a small but diverse group of people to your first event (can ask if this is something they'd be interested in helping build:

    ::: {.callout-note collapse="true"}
    ## Example I used

    Hi {Name}!, I'm reaching out because we're building a new ongoing, community-oriented event for data science leaders. The mission is to highlight the perspective of experts in a casual, conversational setting with no agenda or slides...bringing lots of value to anyone in the data science community that chooses to participate.

    Is this something you'd be interested in helping build by being one of the featured leaders? I thought your experience with XYZ would be really valuable to the community.

    Thanks so much!\
    Rachael
    :::

9.  Welcome people into the event by telling them what to expect, explaining how they can ask questions, and letting them know this is a space for everyone (if it is)

10. Write down the names of a few people that joined (maybe start with 5) and connect with them on LinkedIn or send them a message on your internal company channels to say "Thank you for joining the event today!"

11. Share a summary of resources shared, lessons learned, or the recording in your Slack, Teams, Yammer, Discord, etc. of your choice

12. Continue to hold your event consistently ☺️

13. Keep in contact with your attendees and comment on great work they have done. Ask them if they would be interested in sharing that in a few months - then try to lock down a date

14. Ask the group for feedback about what's working well for them and what's not

15. Take time to step back and decide what other opportunities there are for sustaining and growing this community

16. Celebrate the achievements of your community work by sharing with your direct manager and leadership
:::

### What is your goal for you community? 

This will help you determine your strategy.

What first led you to want to create a community? There were probably many points along the way where you thought, "this might be a great idea."

A few goals shared from other organizers:

-   Create internal connections: many data scientists may work along in different business units, so it's helpful to learn about others across the work.\
-   Increase collaboration: Draw on the creativity and power of a broad community across the company and work together to solve common problems.\
-   Grow the use of data science: Increase data literacy across the company by providing space for people to learn how to get started

If you're not 100% sure on your goals and strategy, don't worry. Sometimes just getting started can be the best way.

::: callout-tip
Think of this as an experiment. It's okay to try new things and see what works best. Everything isn't set in stone. Experiment to see what works well for people across your company - every team may be different.
:::

### Community isn't one single thing.

Community is a lot of little -- and big things together. There are a lot of organizations taking a multi-pronged approach to community building. It's not just having a Slack channel or Teams channel, it's also different events, the way that you engage people across the company, etc.

In a recent R/Pharma workshop, there was a Community Building Workshop, which highlighted 3 companies upfront (AstraZeneca, Pfizer, and Johnson & Johnson) and the different initiatives that they lead.

Community in these organizations includes many things like:

-   Monthly initiatives promoting a package or function as a blog post
-   TidyTuesday with a company dataset
-   Showcasing a community leader each month from the organization and asking them 10 questions
-   Monthly community meetings with 2 presentations each month
-   Monthly newsletter curated for the community
-   Annual conference (for ex: Shiny Day) with live workshop & half day of groups presenting their apps/use-cases
-   Central repository with all material: learning pathways, internal videos, etc.

### Be consistent.

Building communities takes time. People need to know what to expect and when.

Rachael Dempsey shared in her [2022 RStudio Conference talk](https://www.rstudio.com/conference/2022/talks/everything-learned-community-building-learned/), that much of what she learned about community building actually came from growing up in a restaurant.

::: {.callout-tip collapse="true"}
## Here's that section of the conference talk

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/s0ZU4FDstfY?start=142" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```
:::

At many restaurants there are certain days that are often associated with certain foods or certain events. One easy one to remember is Taco Tuesday. People don't come to every single Tuesday, but when they have a free night or when they're looking for something to do with friends, they know exactly where they can go. It remains top of mind on a Tuesday.

We've seen consistency work for many community initiatives:

-   Every Thursday at 12 ET, Posit hosts a Data Science Hangout. Every week a different data science leader from the community joins as a co-host to answer questions from the community. There's no presentation at these sessions and all the questions are audience led. A few examples: How do I talk to executives? How are you thinking about hiring right now? Should I have a centralized or decentralized data science team?
-   At John Deere, they host bi-weekly office hours for a variety of different tools (PowerBI, Tableau, Posit Team, etc.) for beginners to bring their questions and connect with each other and power users.
-   AstraZeneca hosts a Lunch & LeaRn that takes place at lunchtime, alternating between European and US timezones.

It's important to point out that just because you hold events consistently doesn't mean everyone will show up right away. It takes some time for things to catch on - and also requires incorporating the other tips below.

### Standardize where possible

In being consistent, you are able to standardize as much as possible. Whether it's office hours or a monthly meetup, you can create an event invitation, logo, and format that you use every time. This can help take care of a lot of the planning and also scheduling. When you have specific dates and times each week or month, you can schedule people into those slots as it fits their schedule rather than having to change each event to fit a specific speaker's calendar. Once you get going and planning a few months out, this will become easier.

::: {.callout-tip collapse="true"}
## Regis James shared his thoughts on achieving scalability through standardizing at a Data Science Hangout

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/hjufaKBU6Ec?start=1144" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

Regis James, Senior Manager (Biopharmaceutical Data Science) at Regeneron Pharmaceuticals shared:


In order to achieve scalability I do have to standardize things a bit. We use Confluence, so on the wiki that I've made, I have a lockdown page where I have some standardized messages that I send out to people at different phases of things.

I do customize and read what people say about themselves and I'm thinking, “this could be useful here, that could be useful there.”

One of the things that I do is– I have this whole ingestion pipeline that I maintain to identify new members of the community and who can help the community learn more about the blockers to current responsibilities they have for their job.

All companies have a directory where you can learn about who exists at the company and see people's job titles.

I can look into the directory for data or data science or whatever and see if the people that come out in the results are already in my Microsoft Teams group because they could be potential new people who could benefit from being in the community.

They might be able to do their job better and also help other people do their job better, if they can connect to others who have similar needs or can offer similar things.

I do this on a semi-regular basis, so I can really help onboard people who have just joined the company or maybe moved into a data science type role.

Then I reach out to these people, and use my standardized message like, “Hey, I just want you to know this group exists. This community was built just for people like you. This is what we do and here's a link to the wiki that has the links of all the recordings” - because we have a growing library of all the conversations just like the Hangouts.

I only send one email and ask people to let me know if they’re interested in it. I don't spam people.

Of the subset, who answer - sometimes it's like 20% that respond, they say, “Yes, this is amazing. Thank you for letting me know. I just came to the company. I didn't even know if there was a community.” I'm also doing it from my own perspective of when I joined the company. 

When they respond and then they say they're interested, I add them to the Teams group, to the Active Directory group, and then forward the invitation to the ongoing gatherings every other Friday.

In the invitation text I paste in, “Welcome to the group. Please introduce yourself in the introduction section" and include a link that takes them directly into not just the Team for the group, but the channel of introductions.

Since doing this, I've gotten a lot higher percentage of people who have been added to the group to start introducing themselves and say what they work on.

I see what people are working on, and integrate that with my understanding of what people need help with from the Shiny app (the poll for what talks people are interested in.)

Then I reach out to them and say, “Hey, would you be interested in being one of the guests for an upcoming event?” I send them the link and they can see there's no pressure because I'm a year out. I've got someone every other week. So it's like, Hey, would this be something you’re interested in and then I am gently having a conversation over time.

Sometimes people drop out and I just reach out to those people and ask if they would be able to switch.
:::

### Find your core group

Be intentional when starting your core group. Try to include a diverse group of people across the company from the very beginning.

When finding people who may be interested, think about who you may already know from your company. Have you seen other presentations by people at your company at industry conferences or other internal groups? What about on LinkedIn or Twitter? These are great people to reach out to from the start.

You can also use LinkedIn to find people from your company who may be interested. For advanced search functionality, you can do a [30-day free trial of LinkedIn Sales Navigator](https://business.linkedin.com/sales-solutions/compare-plans). This will allow you to search for those at your company who are also in groups like:

-   "R Project for Statistical Computing"
-   "Python Developers Community."

### Be your own marketing team

You can do it! Branding and making things look pretty is surprisingly (or maybe not surprising) very important.

One tool that makes this easier is [Canva](https://www.canva.com/). Canva is an online design and publishing tool with a mission to empower everyone in the world to design anything and publish anywhere. You can create a free account to easily create logos and event images.

As mentioned earlier with standardizing, try to find an event image format that you like and use this each month and adjust the speaker/title. It will make your life a lot easier than having to recreate the wheel every month and will also help people recognize your community events.
