---
title: Community Resources & Examples
---

### Data Science Community Examples in the wild: 
-   [R @ AZ: Building a Community in the Pharmaceutical Industry](https://www.rstudio.com/blog/building-a-community-in-the-pharmaceutical-industry/)
-   [World Bank Shiny Day](https://www.worldbank.org/en/events/2021/04/28/-r-shiny-days#overview)
-   [NHS R Community](https://nhsrcommunity.com/)
-   [NHS-R Community Podcast: Pfizer R Centre of Excellence](https://soundcloud.com/nhs-r-community/pfizer?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing)

### Community Building Resources
-   "There's only one R in Pfizer: Attempts to harmonise R release across a large pharma organisation" - Mike Smith - [View talk](https://www.youtube.com/watch?v=bnRdI6jvGpM)
-   "A Journey to Data Science: Tools for Equity and Diversity in STEM" - Ileana Fenwick - [View talk](https://youtu.be/q4E5Z1B4IQA)
-   "We R KaggleRs - At the Intersection of Data Science Communities" - Martin Henze - [View talk](https://youtu.be/WAp82jxf9RA)
-   "R at AstraZeneca: upskilling our workforce through education, experience, and exposure" [View talk](https://youtu.be/YfTIwi-KOts)
-   "Communicating the value of data science" - Merav Yuravlivker - [View talk](https://youtu.be/xR9kGAZXpV4)
-   R User Group Community Explorer - [View App](https://benubah.github.io/r-community-explorer/rugs.html)
-   "Everything I learned about community building from growing up in a bar" - Rachael Dempsey - [View blog](https://rachaeldempsey.quarto.pub/community-corner-blog/posts/post-with-code/#drink)